"""Contract test (P0.3): the MCP adapter (server.py) vs the execution contract.

Guards against drift between the model-facing MCP surface generated by FastMCP
from `server.py` and the hand-maintained low-level tool contract at
`solidworks-execution/contracts/tool-schemas.json`. If a tool or a parameter is
added/removed/renamed on one side but not the other, this test fails.

Scope: structural drift only — the SET of tools, and the SET of parameter names
per tool. (The contract stores prose-valued params, not machine types, so deeper
type/enum checks would be brittle; those live in server.py's Literal/Field
constraints, exercised by the live smoke test.)

Runnable two ways:
  - standalone:  python tests/test_schema_contract.py   (exits non-zero on drift)
  - pytest:      pytest tests/test_schema_contract.py
"""
import asyncio
import json
import os
import sys

_HERE = os.path.dirname(os.path.abspath(__file__))
_ADAPTER_DIR = os.path.dirname(_HERE)
_REPO_ROOT = os.path.dirname(os.path.dirname(_ADAPTER_DIR))
_CONTRACT_PATH = os.path.join(
    _REPO_ROOT, "solidworks-execution", "contracts", "tool-schemas.json"
)

# Import server.py as a module (it lives one dir up from tests/).
sys.path.insert(0, _ADAPTER_DIR)
import server  # noqa: E402


def _adapter_tools():
    """{tool_name: set(param_names)} from the FastMCP-generated schema."""
    tools = asyncio.run(server.mcp.list_tools())
    out = {}
    for t in tools:
        props = (t.parameters or {}).get("properties", {})
        out[t.name] = set(props.keys())
    return out


def _contract_tools():
    """{tool_name: set(param_names)} from tool-schemas.json (params sub-dict)."""
    with open(_CONTRACT_PATH, encoding="utf-8") as fh:
        contract = json.load(fh)
    out = {}
    for name, spec in contract.items():
        params = (spec.get("input") or {}).get("params") or {}
        out[name] = set(params.keys())
    return out


def find_drift():
    """Return a list of human-readable drift messages (empty == in sync)."""
    adapter = _adapter_tools()
    contract = _contract_tools()
    errors = []

    only_adapter = sorted(set(adapter) - set(contract))
    only_contract = sorted(set(contract) - set(adapter))
    for name in only_adapter:
        errors.append(f"tool '{name}' is exposed by server.py but missing from tool-schemas.json")
    for name in only_contract:
        errors.append(f"tool '{name}' is in tool-schemas.json but not exposed by server.py")

    for name in sorted(set(adapter) & set(contract)):
        a, c = adapter[name], contract[name]
        missing_in_contract = sorted(a - c)
        missing_in_adapter = sorted(c - a)
        if missing_in_contract:
            errors.append(f"tool '{name}': params {missing_in_contract} in server.py but not in tool-schemas.json")
        if missing_in_adapter:
            errors.append(f"tool '{name}': params {missing_in_adapter} in tool-schemas.json but not in server.py")
    return errors


def test_schema_contract_in_sync():
    """pytest entry point."""
    errors = find_drift()
    assert not errors, "MCP/contract drift detected:\n  - " + "\n  - ".join(errors)


if __name__ == "__main__":
    errs = find_drift()
    if errs:
        print("CONTRACT DRIFT DETECTED:")
        for e in errs:
            print("  -", e)
        sys.exit(1)
    counts = _adapter_tools()
    print(f"OK - {len(counts)} tools in sync (server.py <-> tool-schemas.json)")
    sys.exit(0)
